#!/bin/bash

set -e

cp -rp docroot/* $OUTPUT_ARTIFACTS_DIR/
(cd $INPUT_ARTIFACTS_DIR/weak/meta_tools.release/strong/meta_tools.release && tar -czf $OUTPUT_ARTIFACTS_DIR/qbt-release.tar.gz *)
# place version file so we know what version of meta_tools we have
cp $INPUT_ARTIFACTS_DIR/weak/meta_tools.release/strong/meta_tools.release/qbt.versionDigest $OUTPUT_ARTIFACTS_DIR/meta_tools.release.version
# create the build timestamp
echo $(date) > $OUTPUT_ARTIFACTS_DIR/meta_tools.release.date
cp -rp $INPUT_ARTIFACTS_DIR/strong/qbt.docs/docs $OUTPUT_ARTIFACTS_DIR/

